name: Remote Commands

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Remote Commands
        run: |
          cat ${{ secrets.SSH_PRIVATE_KEY }} > tstActionz
          sudo chmod 0400 tstActionz
          ssh -v -o StrictHostKeyChecking=no -i tstActionz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'ls /'
