on:
  push:
    branches:
      - main

jobs:
  run_pull:
  # - name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

    
      - name: list directory
        run: |
         echo "${{ secrets.SSH_P_KEYS }}" > tstActions.pem
         chmod 0400 tstActions.pem
         ssh -i tstActions.pem ${{ secrets.SSH_HOST }} "ls ~/actions"
