name: Remote Commands

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p .ssh
          echo "${{ secrets.SSH_P_KEYS }}" > .ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server >> .ssh/known_hosts

      - name: Run Remote Commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls /"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_P_KEYS }}
