on:
  push:
    branches:
      - main

jobs:
  run_pull:
  # - name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

    
      - name: list directory
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_P_KEY }}"
          "ls /"
