name: Remote Commands

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Remote Commands
        run: |
          mkdir -p /home/runner/.ssh/
          echo "${{ secrets.SSH_HOST }}" >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/tstActionz.pem
          chmod 600 /home/runner/.ssh/tstActionz.pem
          ssh -v -o StrictHostKeyChecking=no -i /home/runner/.ssh/tstActionz.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'ls /'
